version: "3.9"

services:
  python-ai:
    build: ./backend-python
    container_name: python-ai
    ports:
      - "5000:5000"  # Host:Container
    restart: unless-stopped
    networks: [traceit-net]

  node-backend:
    build: ./backend-node
    env_file: ./backend-node/.env
    container_name: node-backend
    ports:
      - "3000:3000"  # Host:Container
    restart: unless-stopped
    depends_on: [python-ai]
    networks: [traceit-net]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000/api
    container_name: frontend
    ports:
      - "3001:80"
    depends_on: [node-backend]
    networks: [traceit-net]

networks:
  traceit-net: